"""Shared model paths — generates extra_model_paths.yaml per installation.

When a shared_dir is configured, this module generates a YAML config file
that tells ComfyUI to use the shared directory for models.  Input, output,
and user directories are handled separately via CLI args (--input-directory,
--output-directory) because ComfyUI doesn't support them in the YAML config.

The generated file is stored at {install_path}/.comfy-runner-extra-models.yaml
and passed via --extra-model-paths-config at launch time.
"""

from __future__ import annotations

import os
from pathlib import Path

# Known model folder types from ComfyUI's folder_paths.py
# These are enumerated explicitly for compatibility with ComfyUI versions
# that don't support the all_model_folders flag.
KNOWN_MODEL_FOLDERS = [
    "checkpoints",
    "classifiers",
    "clip_vision",
    "configs",
    "controlnet",
    "diffusers",
    "diffusion_models",
    "embeddings",
    "gligen",
    "hypernetworks",
    "loras",
    "photomaker",
    "style_models",
    "text_encoders",
    "upscale_models",
    "vae",
    "vae_approx",
    "latent_upscale_models",
    "model_patches",
    "audio_encoders",
]

# Canonical names + legacy aliases that ComfyUI maps to canonical names
_KNOWN_SET = frozenset(KNOWN_MODEL_FOLDERS) | frozenset([
    "clip",          # legacy alias → text_encoders
    "unet",          # legacy alias → diffusion_models
    "t2i_adapter",   # secondary dir for controlnet
])

# Non-model shared directories (handled via CLI args, not YAML)
SHARED_IO_DIRS = ["input", "output"]

GENERATED_YAML_NAME = ".comfy-runner-extra-models.yaml"


def get_extra_models_path(install_path: str | Path) -> Path:
    """Return the path to the generated extra_model_paths.yaml for an installation."""
    return Path(install_path) / GENERATED_YAML_NAME


def generate_extra_model_paths_yaml(
    shared_dir: str | Path,
    extra_folders: list[str] | None = None,
) -> str:
    """Generate the YAML content for extra_model_paths.yaml.

    Uses all_model_folders for future-proofing, plus explicit entries
    for compatibility with older ComfyUI versions.  *extra_folders*
    are non-canonical folder names discovered from custom nodes.
    """
    shared = Path(shared_dir).resolve()
    models_dir = shared / "models"

    all_folders = list(KNOWN_MODEL_FOLDERS)
    if extra_folders:
        all_folders.extend(extra_folders)

    lines = [
        "# Auto-generated by comfy-runner — do not edit manually",
        "# Shared model paths configuration",
        "",
        "comfy_runner_shared:",
        f"    base_path: {models_dir}",
        "    is_default: true",
    ]

    # Explicit entries for each model folder type
    # (ComfyUI iterates remaining keys as folder_name: relative_path)
    for folder in all_folders:
        lines.append(f"    {folder}: {folder}/")

    lines.append("")
    return "\n".join(lines)


def get_shared_io_args(shared_dir: str | Path) -> list[str]:
    """Return CLI args for shared input/output directories.

    ComfyUI uses --input-directory and --output-directory (not YAML)
    for these paths.
    """
    shared = Path(shared_dir).resolve()
    args: list[str] = []
    input_dir = shared / "input"
    output_dir = shared / "output"
    if input_dir.exists():
        args.extend(["--input-directory", str(input_dir)])
    if output_dir.exists():
        args.extend(["--output-directory", str(output_dir)])
    return args


def write_extra_model_paths(
    install_path: str | Path,
    shared_dir: str | Path,
    extra_folders: list[str] | None = None,
) -> Path:
    """Generate and write the extra_model_paths.yaml for an installation.

    Returns the path to the written file.
    """
    yaml_path = get_extra_models_path(install_path)
    content = generate_extra_model_paths_yaml(shared_dir, extra_folders)
    yaml_path.write_text(content, encoding="utf-8")
    return yaml_path


def ensure_shared_dirs(shared_dir: str | Path) -> None:
    """Create the shared directory structure if it doesn't exist."""
    shared = Path(shared_dir)
    shared.mkdir(parents=True, exist_ok=True)

    # Models subdirectories
    models_dir = shared / "models"
    for folder in KNOWN_MODEL_FOLDERS:
        (models_dir / folder).mkdir(parents=True, exist_ok=True)

    # IO directories
    for d in SHARED_IO_DIRS:
        (shared / d).mkdir(parents=True, exist_ok=True)


def remove_extra_model_paths(install_path: str | Path) -> None:
    """Remove the generated extra_model_paths.yaml from an installation."""
    yaml_path = get_extra_models_path(install_path)
    yaml_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Model folder discovery and sync
# ---------------------------------------------------------------------------

def _list_subdirs(directory: str | Path) -> list[str]:
    """List subdirectory names in *directory*, including symlinks to dirs."""
    d = Path(directory)
    if not d.is_dir():
        return []
    result = []
    try:
        for entry in os.scandir(d):
            if entry.is_dir(follow_symlinks=True):
                result.append(entry.name)
    except OSError:
        pass
    return result


def discover_extra_model_folders(install_path: str | Path) -> list[str]:
    """Scan the installation's models dirs for non-canonical folder types.

    Checks both ``{install}/ComfyUI/models`` (standalone layout) and
    ``{install}/models`` (portable).  Returns sorted list of extra names.
    """
    candidates = [
        Path(install_path) / "ComfyUI" / "models",
        Path(install_path) / "models",
    ]
    seen: set[str] = set()
    for d in candidates:
        for name in _list_subdirs(d):
            if name not in _KNOWN_SET:
                seen.add(name)
    return sorted(seen)


def sync_custom_model_folders(
    install_path: str | Path,
    shared_dir: str | Path,
    previous_extras: list[str] | None = None,
) -> dict:
    """Sync model folders from the installation to the shared directory.

    1. Scans the install for ALL model subdirectories (canonical + extra).
    2. Creates matching directories in the shared models root.
    3. Rewrites the YAML to include any extra (non-canonical) folders.

    Returns ``{"new_folders": [...], "extra_folders": [...], "yaml_path": ...}``.
    *new_folders* contains only folders not in *previous_extras* — this is
    what callers use to decide whether a restart is needed.
    """
    shared = Path(shared_dir).resolve()
    shared_models = shared / "models"

    # Collect ALL model folders from the installation
    candidates = [
        Path(install_path) / "ComfyUI" / "models",
        Path(install_path) / "models",
    ]
    all_install_folders: set[str] = set()
    for d in candidates:
        all_install_folders.update(_list_subdirs(d))

    # Ensure every folder exists in the shared dir
    for folder in all_install_folders:
        (shared_models / folder).mkdir(parents=True, exist_ok=True)

    # Also discover extras already in shared dirs (from previous syncs)
    extra_in_shared = {
        name for name in _list_subdirs(shared_models)
        if name not in _KNOWN_SET
    }
    # Extras from the installation
    extra_in_install = {
        name for name in all_install_folders
        if name not in _KNOWN_SET
    }
    all_extras = sorted(extra_in_shared | extra_in_install)

    # Determine which are genuinely new
    prev_set = set(previous_extras) if previous_extras else set()
    new_folders = [f for f in all_extras if f not in prev_set]

    # Rewrite the YAML with extra folders included
    yaml_path = write_extra_model_paths(install_path, shared_dir, all_extras or None)

    return {
        "new_folders": new_folders,
        "extra_folders": all_extras,
        "yaml_path": str(yaml_path),
    }
